### ISSUE TITLE
Custom Image Documentation 

### ISSUE THREAD

**Issue by relyt0925** [ibm-cloud-docs/vpc#33]
Custom Image Documentation 

We recently went through the process of exporting a custom image from classic into vpc next gen and hit a couple gotchas that we thought would be helpful to document in the VPC docs as well as some useful debugging tips that users can use to test the image before importing.

**Ubuntu** :

Requirements:

- Cloud-init must be installed

- The default cloud-config file at `/etc/cloud/cloud.cfg` that is installed should be used. Don't modify this file. 

- NetworkManager must be disabled (systemctl disable NetworkManager)

- We also had to resize the image after running 
```
#export to cos
slcli image export "$image_id" "cos://${ORIGIN_COS_BUCKET_REGION}/${ORIGIN_COS_BUCKET_NAME}/${image_captured_name}.vhd" --ibm-api-key "$ORIGIN_COS_BX_APIKEY"  

#download from COS
ibmcloud cos download --bucket "$ORIGIN_COS_BUCKET_NAME" --key "${image_captured_name}${softlayer_export_cos_suffix}" "$(pwd)/${image_captured_name}.vhd"

#convert to qcow2
./qemu-img convert -O qcow2 "$(pwd)/${image_captured_name}.vhd" "$(pwd)/${image_captured_name}.qcow2"

#resize to ensure image boots appropriately
./qemu-img resize "$(pwd)/${image_captured_name}.qcow2" +256M
```

**RHEL 7**:
- Cloud-init must be installed and enabled (not installed by default in classic)

- The following `/etc/cloud/cloud.cfg` file must be used:
```
# Configure the Datasource for both instances
datasource_list: [ ConfigDrive, NoCloud ]

user: root
ssh_pwauth: True
disable_root: False
manage_etc_hosts: True

system_info:
  # This will affect which distro class gets used
  distro: rhel
  # Other config here will be given to the distro class and/or path classes
  paths:
    cloud_dir: /var/lib/cloud
    templates_dir: /etc/cloud/templates

cloud_init_modules:
  - migrator
  - seed_random
  - bootcmd
  - write-files
  - disk_setup
  - mounts
  - ca-certs
  - rsyslog
  - users-groups

cloud_config_modules:
  # Emit the cloud config ready event
  # this can be used by upstart jobs for 'start on cloud-config'.
  - snap_config
  - locale
  - set-passwords
  - ntp
  - timezone
  - disable-ec2-metadata
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - yum_add_repo
  - runcmd

cloud_final_modules:
  - snappy
  - package-update-upgrade-install
  - fan
  - lxd
  - puppet
  - chef
  - salt-minion
  - mcollective
  - rightscale_userdata
  - scripts-vendor
  - scripts-per-once
  - scripts-per-boot
  - scripts-per-instance
  - scripts-user
  - ssh-authkey-fingerprints
  - keys-to-console
  - phone-home
  - final-message
  - power-state-change
```

- NetworkManager must be disabled (systemctl disable NetworkManager)

- We also had to resize the image before we imported it in the environment similar to the steps listed in the Ubuntu section

Debugging tips:

While there is no option for KVM in VPC currently a user can do a debugging step locally if they have qemu installed. They can proceed to take the qcow2 image they created and attempt to boot it locally on their work station with:
```
qemu-system-x86_64 -m 2048 -hda /Users/myuser/Downloads/UBUNTU_18_04_64_100GB_VPC_CONTAINER_SERVICE_0.0.9.qcow2
```

This will open a terminal window for them locally that will allow them to view early boot logs. These boot logs can offer important clues if there's a bug or misconfiguration in the image that will ultimately prevent the image from booting in the VPC environment.
